// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjfngskbELwbgwp0TS43lc_mHJ0qLt7sY',
    appId: '1:121298934600:web:2723e7841d777ed184717d',
    messagingSenderId: '121298934600',
    projectId: 'modul-12-40bad',
    authDomain: 'modul-12-40bad.firebaseapp.com',
    storageBucket: 'modul-12-40bad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKHN6Kvib3VWyIDTG4xSdxmaJjh_sftwg',
    appId: '1:121298934600:android:13a20d143a5b053e84717d',
    messagingSenderId: '121298934600',
    projectId: 'modul-12-40bad',
    storageBucket: 'modul-12-40bad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWj0NKfKY-54rAbMoe9kYA4u1mE5ZlM6Q',
    appId: '1:121298934600:ios:65e1e9cf06e89cab84717d',
    messagingSenderId: '121298934600',
    projectId: 'modul-12-40bad',
    storageBucket: 'modul-12-40bad.firebasestorage.app',
    iosBundleId: 'com.example.mod12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWj0NKfKY-54rAbMoe9kYA4u1mE5ZlM6Q',
    appId: '1:121298934600:ios:65e1e9cf06e89cab84717d',
    messagingSenderId: '121298934600',
    projectId: 'modul-12-40bad',
    storageBucket: 'modul-12-40bad.firebasestorage.app',
    iosBundleId: 'com.example.mod12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjfngskbELwbgwp0TS43lc_mHJ0qLt7sY',
    appId: '1:121298934600:web:ddbbcd591ab020e984717d',
    messagingSenderId: '121298934600',
    projectId: 'modul-12-40bad',
    authDomain: 'modul-12-40bad.firebaseapp.com',
    storageBucket: 'modul-12-40bad.firebasestorage.app',
  );
}
